var annotated_dup =
[
    [ "Core", "namespaceCore.html", [
      [ "Context", "classCore_1_1Context.html", "classCore_1_1Context" ],
      [ "Drawable", "classCore_1_1Drawable.html", null ],
      [ "IndexBuffer", "classCore_1_1IndexBuffer.html", null ],
      [ "Matrices", "structCore_1_1Matrices.html", null ],
      [ "Program", "classCore_1_1Program.html", null ],
      [ "Shader", "classCore_1_1Shader.html", null ],
      [ "Texture", "classCore_1_1Texture.html", null ],
      [ "UniformBuffer", "classCore_1_1UniformBuffer.html", null ],
      [ "VertexArray", "classCore_1_1VertexArray.html", "classCore_1_1VertexArray" ],
      [ "VertexBuffer", "classCore_1_1VertexBuffer.html", null ]
    ] ],
    [ "fmt", null, [
      [ "formatter< glm::mat< C, R, Pre > >", "structfmt_1_1formatter_3_01glm_1_1mat_3_01C_00_01R_00_01Pre_01_4_01_4.html", null ],
      [ "formatter< glm::vec< L, Pre > >", "structfmt_1_1formatter_3_01glm_1_1vec_3_01L_00_01Pre_01_4_01_4.html", null ],
      [ "formatter< Util::Transform >", "structfmt_1_1formatter_3_01Util_1_1Transform_01_4.html", null ]
    ] ],
    [ "Util", "namespaceUtil.html", [
      [ "Animation", "classUtil_1_1Animation.html", "classUtil_1_1Animation" ],
      [ "AssetStore", "classUtil_1_1AssetStore.html", "classUtil_1_1AssetStore" ],
      [ "BGM", "classUtil_1_1BGM.html", "classUtil_1_1BGM" ],
      [ "Color", "classUtil_1_1Color.html", "classUtil_1_1Color" ],
      [ "CustomizableImage", "classUtil_1_1CustomizableImage.html", "classUtil_1_1CustomizableImage" ],
      [ "GameObject", "classUtil_1_1GameObject.html", "classUtil_1_1GameObject" ],
      [ "Image", "classUtil_1_1Image.html", "classUtil_1_1Image" ],
      [ "ImageArray", "classUtil_1_1ImageArray.html", "classUtil_1_1ImageArray" ],
      [ "Input", "classUtil_1_1Input.html", null ],
      [ "Renderer", "classUtil_1_1Renderer.html", "classUtil_1_1Renderer" ],
      [ "SFX", "classUtil_1_1SFX.html", "classUtil_1_1SFX" ],
      [ "SpriteSheetAnimation", "classUtil_1_1SpriteSheetAnimation.html", "classUtil_1_1SpriteSheetAnimation" ],
      [ "Text", "classUtil_1_1Text.html", "classUtil_1_1Text" ],
      [ "Time", "classUtil_1_1Time.html", null ],
      [ "Transform", "structUtil_1_1Transform.html", "structUtil_1_1Transform" ]
    ] ],
    [ "ADVPowerPlants", "classADVPowerPlants.html", null ],
    [ "App", "classApp.html", null ],
    [ "AttackAndDamage", "classAttackAndDamage.html", null ],
    [ "Avatar", "classAvatar.html", null ],
    [ "AvatarManager", "classAvatarManager.html", null ],
    [ "AvatarNavigator", "classAvatarNavigator.html", null ],
    [ "AvatarOrder", "classAvatarOrder.html", null ],
    [ "Barracks", "classBarracks.html", null ],
    [ "BuiltStructure", "classBuiltStructure.html", null ],
    [ "CameraClass", "classCameraClass.html", null ],
    [ "CursorClass", "classCursorClass.html", null ],
    [ "CursorSelection", "classCursorSelection.html", null ],
    [ "DefaultScene", "classDefaultScene.html", null ],
    [ "DemoScene", "classDemoScene.html", null ],
    [ "DrawOverlays", "classDrawOverlays.html", null ],
    [ "EnemyPlayer", "classEnemyPlayer.html", null ],
    [ "EnemyScripts", "classEnemyScripts.html", null ],
    [ "GameObjectID", "classGameObjectID.html", null ],
    [ "Grid", "classGrid.html", null ],
    [ "Health", "classHealth.html", null ],
    [ "HighLight", "classHighLight.html", null ],
    [ "House", "classHouse.html", null ],
    [ "Hunter", "classHunter.html", null ],
    [ "IHealthable", "classIHealthable.html", null ],
    [ "Infantry", "classInfantry.html", null ],
    [ "IOrderable", "classIOrderable.html", null ],
    [ "IWayPointStructure", "classIWayPointStructure.html", null ],
    [ "Line", "classLine.html", null ],
    [ "MapBinReader", "classMapBinReader.html", null ],
    [ "MapClass", "classMapClass.html", null ],
    [ "MapScene", "classMapScene.html", null ],
    [ "MapUtil", "classMapUtil.html", null ],
    [ "MenuScene", "classMenuScene.html", null ],
    [ "Moving", "classMoving.html", null ],
    [ "NemesisManager", "classNemesisManager.html", null ],
    [ "OreRefinery", "classOreRefinery.html", null ],
    [ "PathUtility", "classPathUtility.html", null ],
    [ "Player", "classPlayer.html", null ],
    [ "PowerPlants", "classPowerPlants.html", null ],
    [ "Runner", "classRunner.html", null ],
    [ "SandBag", "classSandBag.html", null ],
    [ "Scene", "classScene.html", null ],
    [ "Selectable", "classSelectable.html", null ],
    [ "Sprite", "classSprite.html", null ],
    [ "SpriteSheet", "classSpriteSheet.html", "classSpriteSheet" ],
    [ "Structure", "classStructure.html", null ],
    [ "StructureManager", "classStructureManager.html", null ],
    [ "StructureOrder", "classStructureOrder.html", null ],
    [ "TerrainConfig", "classTerrainConfig.html", null ],
    [ "TileClass", "classTileClass.html", null ],
    [ "TutorialScene", "classTutorialScene.html", null ],
    [ "UIClass", "classUIClass.html", null ],
    [ "UIScriptProcess", "classUIScriptProcess.html", null ],
    [ "UnitManager", "classUnitManager.html", null ],
    [ "WarFactory", "classWarFactory.html", null ],
    [ "WayPoint", "classWayPoint.html", null ],
    [ "WayPointStructure", "classWayPointStructure.html", null ],
    [ "Weapon", "classWeapon.html", null ],
    [ "YAMLReader", "classYAMLReader.html", null ]
];